version: "3"
services:
  nginx:
    restart: always
    image: mine0702/docker-nginx
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443" # HTTPS 포트 추가
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /letsencrypt/certbot/conf:/etc/letsencrypt
      - /letsencrypt/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend:
    image: mine0702/docker-frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  backend:
    image: mine0702/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    stdin_open: true
    mem_limit: 128m
