version: "3.9"
services:
  frontend:
    image: mine0702/docker-frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: mine0702/docker-nginx
    container_name: app_nginx
    ports:
      - "80:80"

  backend:
    image: mine0702/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    stdin_open: true
    mem_limit: 128m
